# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Historial de Productos
products = Product.create([
    {name: "Samsung UN58MU6100 58-Inch 4K Ultra HD Smart LED", image: "https://images-na.ssl-images-amazon.com/images/I/61rS%2BdaSxqL._SX522_.jpg", description: "The Samsung MU6100 Ultra HDTV redefines the viewing experience by producing a colorful High Dynamic Range (HDR) picture. Our new Smart TV user-interface (UI), faster running streaming services with Quad Core Processing, and mobile to TV screen mirroring make enjoying personal pictures and videos a cinch.", price: 747.99, quantity: 15},
    {name: "TCL 49S405 49-Inch 4K Ultra HD Roku Smart LED", image: "https://images-na.ssl-images-amazon.com/images/I/51vL5SQbwaL._SX425_.jpg", description: "We've simplified the 4k Ultra HD TV so you can instantly enjoy endless entertainment. With HRD compatibility, choose from more than 4,000 streaming channels that feature 450,000 movies and TV episodes plus live sports, news, music, kids and family, food, science and tech, fitness, foreign language and so much more.", price: 349.99, quantity: 20},
    {name: "Sony XBR49X800E 49-Inch 4K Ultra HD Smart LED", image: "https://images-na.ssl-images-amazon.com/images/I/71kj3MtusQL._SX522_.jpg", description: "Enjoy truly remarkable 4K HDR clarity, colour and contrast. Rediscover every detail in 4K HDR while TRILUMINOS Display adds a brilliant picture that’s closer than ever to real-world colours. And with Android TV, find all the entertainment you want, faster than ever.", price: 698.00, quantity: 15},
    {name: "LG Electronics OLED65C7P 65-Inch 4K Ultra HD Smart Oled", image: "https://images-na.ssl-images-amazon.com/images/I/81ocWsPIM4L._SX425_.jpg", description: "Behold movies and more from the most popular providers, brought to life with intense cinematic colors against the ultimate backdrop of perfect black. Discover the most HDR entertainment choices, while Dolby Atmos audio completes this uncompromising home cinema experience.", price: 2696.99, quantity: 25},
    {name: "LG G6", image: "https://images-na.ssl-images-amazon.com/images/I/71RVWfKZk%2BL._SY550_.jpg", description: "The LG G6 is masterfully engineered to give you both a large screen and in-hand comfort. Enjoy an incredible viewing experience on the 5.7-inch QHD Plus FullVision display featuring Dolby Vision technology. Now, you can get more in every shot with wide-angle lenses on both the 5 MP front and 13 MP rear cameras.", price: 638.00, quantity: 24},
    {name: "Apple iPhone X", image: "https://images-na.ssl-images-amazon.com/images/I/51qibZNVexL._SY550_.jpg", description: "iPhone X features an all-screen design with a 5.8-Inch super Retina HD display with HDR and true tone. Face ID lets you unlock and use Apple pay with just a glance. Powered by A11 Bionic, the most powerful and smartest chip ever in a smartphone. Supports augmented reality experiences in games and apps.", price: 1298.98, quantity: 14},
    {name: "Samsung Galaxy S8", image: "https://images-na.ssl-images-amazon.com/images/I/61obKqf3WXL._SY550_.jpg", description: "Meet the Galaxy S8+ - Infinitely Brilliant. The Galaxy S8+ has the world's first Infinity Screen, A screen without limits. The expansive display stretches from edge to edge, giving you the most amount of screen in the least amount of space. The revolutionary design of the Galaxy S8+ begins from the inside out.", price: 718.99, quantity: 16},
    {name: "LeEco Le S3", image: "https://images-na.ssl-images-amazon.com/images/I/71ZIL7JPk1L._SY550_.jpg", description: "Le S3 delivers best-in-class performance by combining the Qualcomm Snapdragon 652 processor, 3GB memory, 32GB onboard storage and LTE-A connectivity. 16MP main and 8MP selfie cameras deliver high resolution photos and videos, paired with an intelligent fingerprint scanner that also acts as a camera shutter button.", price: 129.99, quantity: 19},
    {name: "Nikon D3300", image: "https://images-na.ssl-images-amazon.com/images/I/814ypO5IUaL._SX425_.jpg", description: "Capture every special moment in the lifelike quality it deserves--and have a great time doing it! With its included zoom lens, the new ultra-compact AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR II, the D3300 is a small, easy to use HD-SLR.", price: 499.95, quantity: 24},
    {name: "Canon EOS 60D", image: "https://images-na.ssl-images-amazon.com/images/I/41x470rUwQL._SX425_.jpg", description: "With the new EOS 60D DSLR, Canon gives the photo enthusiast a powerful tool fostering creativity, with better image quality, more advanced features and automatic and in-camera technologies for ease-of-use.", price: 779.99, quantity: 20},
    {name: "Pentax K-1", image: "https://images-na.ssl-images-amazon.com/images/I/81NpX%2B7Y71L._SX425_.jpg", description: "The K-1 is engineered to incorporate all of the performance requirements of high resolution full frame 35mm digital photography, adding PENTAX unique performance features and characteristics.", price: 1799.00, quantity: 21},
    {name: "Sony A77II", image: "https://images-na.ssl-images-amazon.com/images/I/914J1Pyr2gL._SX425_.jpg", description: "Capture the moment more decisively than ever before. Sony’s A77II delivers the world’s fastest1 shooting at 12 fps, while amazing 79-point Phase Detection AF keeps fast-moving subjects in focus and a 24.3MP sensor delivers stunning and detailed imagery. Even sharing is fast thanks to built-in Wi-Fi and NFC.", price: 1798.00, quantity: 22},
    {name: "Acer Predator Helios 300 G3-571-77QK", image: "https://images-na.ssl-images-amazon.com/images/I/81g7AiqWrtL._SX522_.jpg", description: "Acer Predator Helios 300 G3-571-77QK Gaming Notebook comes with these high level specs: 7th Generation Intel Core i7-7700HQ Processor 2.8GHz with Turbo Boost Technology up to 3.8GHz, 15.6-inch Full HD (1920 x 1080) widescreen LED-backlit IPS display, NVIDIA GeForce GTX 1060 with 6 GB of dedicated GDDR5 VRAM, 16GB DDR4 2400MHz Memory, 256GB SSD.", price: 999.99, quantity: 15},
    {name: "ASUS FX502VM-AS73", image: "https://images-na.ssl-images-amazon.com/images/I/71KsoZqNFNL._SX425_.jpg", description: "ASUS FX502VM-AS73 15.6-inch Full-HD Gaming Laptop, 7th-Gen Core i7, GTX 1060 3GB 16GB DDR4 RAM, 128GB SSD + 1TB HDD with Windows 10. 1x Headphone-out & Audio-in Combo Jack; 1x RJ45 LAN Jack for LAN insert; 1x HDMI; 1x mini Display Port; 3x USB 3.0.", price: 1099.19, quantity: 15},
    {name: "Dell i7577-5241BLK-PUS Inspiron", image: "https://images-na.ssl-images-amazon.com/images/I/81-FfgptKZL._SX425_.jpg", description: "La nueva portátil Inspiron 15 7000 Gaming es una poderosa computadora portátil Gaming de la 7ª generación Intel Core i5, GTX 1060 6GB Graphics, 8GB de memoria, 128GB SSD + 1TB HDD, 15.6 pulgadas.", price: 897.00, quantity: 18},
    {name: "Razer Blade Stealth", image: "https://images-na.ssl-images-amazon.com/images/I/81NGdL8IbGL._SX425_.jpg", description: "The Razer Blade Stealth Ultrabook sets the new standard for ultra-mobility and extreme performance. The incredibly thin 0.52 inch CNC aluminum chassis encases an Intel Core i7 processor, 16GB RAM, 256GB SSD and the most visually stunning 13.3 inch QHD+ display.", price: 1349.99, quantity: 20}
])
